name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v7
        with:
          python-version: 3.14
          cache: 'pip'
      - name: Lint and style check with ruff
        uses: astral-sh/ruff-action@v4.0.0
        with:
          args: "format --check --diff"
      - name: Type check with mypy
        run: mypy

