name: CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
      - uses: isort/isort-action@v1
      - uses: chartboost/ruff-action@v1
